"""Prompt definitions for LLM interactions."""

FORMAT = """
IMPORTANT: When including URLs from the source data, reproduce them EXACTLY as provided. Never alter the URL scheme — if the original URL uses https://, keep https://. Do not downgrade to http:// or modify any part of the URL.

{{
    "summary": "A concise narrative summary of the project's current state, key accomplishments, and overall progress.\\n\\nOutput plain markdown paragraphs separated by a blank line. Use **bold** to highlight critical milestones or deliverable names. Use *italic* for secondary emphasis. Where relevant, include a markdown hyperlink to the most important issue, PR, or resource using [link text](link_url_here). Do NOT use headings or bullet lists — paragraphs only.",

    "riskBlockerActionNeeded": "Markdown bullet list of risks, blockers, and action items. If there are no blockers, output exactly: No explicit blockers reported.\\n\\nUse `- ` for each top-level item. Use `  - ` (two spaces) for nested sub-points. Use **bold** for the category label at the start of each bullet. Where a specific issue or PR is relevant, include a markdown hyperlink using [#issue-number or label](issue_or_label_link_here).\\n\\nExample:\\n- **Blocker:** Known API issue in VendorX requires discussion before a fix can be implemented.\\n  - Meeting scheduled with the team on 2026-04-30.\\n  - Tracked in [Issue #21](issue_link_here).\\n- **Action Needed:** Finalise decision on self-hosting vs. managed service.\\n- **Blocked Issue:** [Issue #34](issue_link_here) is stalled pending outcome of AI workflow testing.",

    "taskDetails": {{
        "completed": "Format EXACTLY as shown — one line per main issue title, followed by tab-indented sub-items. Do NOT use markdown bullets or hyphens here; the system converts them automatically. Where a GitHub issue or PR URL is available, include it as a markdown hyperlink in the title line using [Issue Title](issue_link_here) format.\\n\\nFormat:\\n[Main Issue Title](issue_link_here): Brief description.\\n\\t Specific completed action\\n\\t Another completed action\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\n[Google Service Integrations](link_here): Auth flows and doc generation complete.\\n\\t Tested standalone Service Account JSON example.\\n\\t Completed the Google OAuth flow.\\n\\t Implemented FastAPI endpoints for Docs generator.",

        "inProgress": "Same format as completed — title line then tab-indented sub-items. Include ONLY tasks actively in progress; do NOT repeat completed work. Where a GitHub issue or PR URL is available, include it as a markdown hyperlink in the title line using [Issue Title](issue_link_here) format.\\n\\nFormat:\\n[Main Issue Title](issue_link_here): Brief description of ongoing work.\\n\\t Current task being worked on\\n\\t Another ongoing task\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\n[Google Service Development](link_here): Generator and API endpoints under construction.\\n\\t Building Docs generator with template mapping.\\n\\t Implementing FastAPI endpoints.\\n\\t Starting Inngest service integration.",

        "inReview": "Same format — title line then tab-indented sub-items. Include ONLY tasks currently under code or design review. If nothing is in review, output exactly: Nothing is in review. Where a PR URL is available, include it as a markdown hyperlink in the title line using [PR Title](pr_link_here) format.\\n\\nFormat:\\n[Main Issue Title](issue_link_here): Brief description of work under review.\\n\\t PR or deliverable under review\\n\\t Review or approval status\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\n[Google Docs Generator PR](pr_link_here): Backend improvements awaiting review.\\n\\t [PR #57](pr_link_here) raised and submitted for re-review.\\n\\t Awaiting feedback on FastAPI endpoint design."
    }}
}}
"""  # noqa: E501 -- JSON schema defining the expected LLM output structure.
