"""Prompt definitions for LLM interactions."""

FORMAT = """
{{
    "summary": "A concise narrative summary of the project's current state, key accomplishments, and overall progress.This should be 2 to 3 short paragraphs with no more than 350 words. Focus only on the most important deliverables, milestones, and current priorities.\\n\\nUse proper markdown paragraph breaks between sections for readability. Use **bold** to highlight critical milestones or deliverable names. Use *italic* for secondary emphasis.",
    "riskBlockerActionNeeded": "Detailed Markdown bullet list of any risks, blockers, or critical actions that need immediate attention. If there are no explicit blockers mentioned, state 'No explicit blockers reported.' Include only the most relevant action items, dependencies, or issues that could impact project timeline or success.\\n\\nUse line breaks between different risk categories or action items.\\n\\nUse `- ` for each top-level item. Use `  - ` (two spaces) for nested sub-points. Use **bold** for the category label at the start of each bullet. \\n\\nExample:\\n- **Blocker:** Known API issue in VendorX requires discussion before a fix can be implemented.\\n  - Meeting scheduled with the team on 2026-04-30.\\n  - Tracked in Issue #21.\\n- **Action Needed:** Finalise decision on self-hosting vs. managed service.\\n- **Blocked Issue:** Issue #34 is stalled pending outcome of AI workflow testing.",
    "taskDetails": {{
        "completed": "Format EXACTLY as shown — one line per main issue title, followed by tab-indented sub-items. Do NOT use markdown bullets or hyphens here; the system converts them automatically.\\n\\nFormat:\\nMain Issue Title: Brief description.\\n\\t Specific completed action\\n\\t Another completed action\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\nGoogle Service Integrations: Auth flows and doc generation complete.\\n\\t Tested standalone Service Account JSON example.\\n\\t Completed the Google OAuth flow.\\n\\t Implemented FastAPI endpoints for Docs generator.",
        "inProgress": "Same format as completed — title line then tab-indented sub-items. Include ONLY tasks actively in progress; do NOT repeat completed work.\\n\\nFormat:\\n Main Issue Title: Brief description of ongoing work.\\n\\t Current task being worked on\\n\\t Another ongoing task\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\nGoogle Service Development: Generator and API endpoints under construction.\\n\\t Building Docs generator with template mapping.\\n\\t Implementing FastAPI endpoints.\\n\\t Starting Inngest service integration.",
        "inReview": "Same format as completed — title line then tab-indented sub-items. Include ONLY tasks currently under code or design review. If nothing is in review, output exactly: Nothing is in review.\\n\\nFormat:\\nMain Issue Title: Brief description of work under review.\\n\\t PR or deliverable under review\\n\\t Review or approval status\\n\\nLimit to 4–5 titles, each with 2–4 sub-items.\\n\\nExample:\\nGoogle Docs Generator PR: Backend improvements awaiting review.\\n\\t PR #57 raised and submitted for re-review.\\n\\t Awaiting feedback on FastAPI endpoint design."
    }}
}}
"""  # noqa: E501 -- JSON schema that defines the expected structure of the output.
