import json

import inngest

from app.core.adapters import inngest_client
from app.llm.inngest.summarization import summarization
from app.slack.inngest import fetch_slack


@inngest_client.create_function(
	fn_id="summarization_workflow",
	trigger=inngest.TriggerEvent(event="rt-report-automation/summarization_workflow"),
	retries=2,
)
async def summarization_workflow(ctx: inngest.Context) -> str:
	"""Inngest workflow function to fetch Slack data and generate summaries.

	Orchestrates a two-step workflow:
	1. Fetches standup messages from Slack using the fetch_slack function
	2. Summarizes the fetched data using LLM-based summarization

	Args:
		ctx (inngest.Context): The Inngest context containing SummarizeRequest data:
			- llm_model_overrides (ModelMetadata): LLM model configuration
			- project_metadata (ProjectMetadata): Project details with start/end dates
			- user_metadata (UserMetadata): User information
			- github_metadata (GitHubMetadata): GitHub repository details
			- slack_metadata (SlackMetadata): Slack configuration with channel_slug

	Returns:
		str: The final summary generated by the LLM summarization process.

	Raises:
		Exception: Any errors from the fetch_slack or summarization steps.
	"""
	slack_data = await ctx.step.invoke(
		"fetch_slack",
		function=fetch_slack,
		data=ctx.event.data,
	)

	# Convert slack_data to JSON string
	slack_data = json.dumps(slack_data)

	# Prepare data for the summarization step
	data = dict(ctx.event.data)
	data["data"] = [slack_data]

	return await ctx.step.invoke(
		"invoke",
		function=summarization,
		data=data,
	)
